export const experiences = [
	{
		company: 'Research Institution',
		time: '2020 - Present',
		title: 'Senior Research Scientist',
		location: 'City, Country',
		description: 'Leading research projects in artificial intelligence and machine learning, collaborating with interdisciplinary teams.',
	},
	{
		company: 'University Name',
		time: '2018 - 2020',
		title: 'Postdoctoral Researcher',
		location: 'City, Country',
		description: 'Conducted independent research and supervised graduate students in computational methods.',
	},
	// {
	// 	company: 'Radium Institute (Institut du Radium)',
	// 	time: '1914 - 1934',
	// 	title: 'Director',
	// 	location: 'Paris, France',
	// 	description: 'Led groundbreaking studies on radioactivity and mentored future Nobel Prize laureates.',
	// },
];

export const education = [
	{
		school: 'University Name',
		time: '2014 - 2018',
		degree: 'Ph.D. in Computer Science',
		location: 'City, Country',
		description: 'Dissertation: "Advanced Topics in Machine Learning and Data Analysis"',
	},
	{
		school: 'University Name',
		time: '2012 - 2014',
		degree: 'Master\'s in Computer Science',
		location: 'City, Country',
		description: 'Specialized in artificial intelligence and computational methods.',
	},
	// {
	// 	school: 'University of Paris',
	// 	time: '1891 - 1895',
	// 	degree: 'Master's in Physics and Mathematics',
	// 	location: 'Paris, France',
	// 	description: 'Graduated at the top of her class in physics and second in mathematics.',
	// },
];

export const skills = [
	{
		title: 'Programming Languages',
		description: 'Python, R, JavaScript, C Plus Plus, MATLAB',
	},
	{
		title: 'Machine Learning',
		description: 'Deep Learning, Neural Networks, Statistical Analysis, Data Mining',
	},
	{
		title: 'Research Tools',
		description: 'TensorFlow, PyTorch, Jupyter, Git, LaTeX, Academic Writing',
	},
	// {
	// 	title: 'Experimental Techniques',
	// 	description: 'Spectroscopy, Isolation of Radioactive Elements, Radiation Measurement',
	// },
];

export const publications = [
	{
		title: 'Hallucination and Calibration in Language Models',
		authors: 'Harutyun Harry Ilanyan',
		journal: 'UC Berkeley',
		time: '2025',
		link: 'https://wp.math.berkeley.edu/drp/wp-content/uploads/sites/18/2025/05/2025_Spring_Ilanyan.pdf',
		abstract: 'This comprehensive research investigates the critical challenges of hallucination detection and confidence calibration in large language models (LLMs). The study develops novel methodologies for identifying and mitigating false or fabricated information generated by LLMs, while simultaneously improving their ability to accurately assess and communicate their own uncertainty. Through systematic experimentation on benchmark datasets including TruthfulQA and custom evaluation frameworks, this work proposes innovative calibration techniques that enhance model reliability and trustworthiness. The research contributes both theoretical insights into the probabilistic foundations of language model confidence and practical tools for deploying safer, more dependable AI systems in real-world applications.',
		tags: ['LLM', 'AI Safety', 'Calibration', 'Hallucination Detection', 'Machine Learning', 'NLP']
	},
];
